### ISSUE TITLE
有移植ACE吗？

### ISSUE THREAD

**Issue by zuowanbushiwo** [cpuimage/WebRTC_AECM#1]
这个项目很好，非常适合学习，感谢作者。 ACEM的性能是不是要差一点？有没有测试数据啊，谢谢！

**Comment by cpuimage** [comment]
@zuowanbushiwo 没细致比对过，回头有时间在看看。测试数据的话，百度一下，或者自己找两段音频，混音做一个示例，也不麻烦。
